### ISSUE TITLE
窗口改变后，会一直旋转

### ISSUE THREAD

**Issue by WalterMW** [WarrenJones/react-turnplate#1]
第一次加载组件后，改变可视窗口尺寸，当转盘适配完成时，组件会一直旋转。
只有第一次加载直接改变可视窗口尺寸才会这样
解决办法：
加入下图的判断就好了。
![image](https://user-images.githubusercontent.com/30295075/62434692-f1f10900-b76b-11e9-8607-5921a096b3d8.png)

**Comment by WarrenJones** [comment]
感谢！
