### ISSUE TITLE
npm start报错

### ISSUE THREAD

**Issue by MomoHong** [WarrenJones/react-turnplate#2]
ERROR in ./src/reactTurnPlate.js 6:19
Module parse failed: Unexpected token (6:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import "./turnplate.scss";
| export default class ReactTurnPlate extends React.Component {
“>   static propTypes = {
|     // 奖项列表
|     prizeList: PropTypes.array.isRequired,
 @ ./src/index.js 1:0-46 2:15-29”

**Comment by WarrenJones** [comment]
是不是你没装好相应的loader？

**Comment by MomoHong** [comment]
跑demo，Webpack配置需要自己写吗 我看项目中都没有




在2019年10月09日 14:29，WarrenJones 写道：

是不是你没装好相应的loader？

**Comment by WarrenJones** [comment]
> 跑demo，Webpack配置需要自己写吗 我看项目中都没有 在2019年10月09日 14:29，WarrenJones 写道： 是不是你没装好相应的loader？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

不好意思，补上了。现在可以了

**Comment by WarrenJones** [comment]
如果觉得ok，帮忙点赞哈哈哈哈，感谢您

**Comment by MomoHong** [comment]
没问题！


在2019年10月10日 13:52，WarrenJones<notifications@github.com> 写道：

如果觉得ok，帮忙点赞哈哈哈哈，感谢您
